# Generated by Django 4.1.4 on 2023-05-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='date_time',
        ),
        migrations.AddField(
            model_name='point',
            name='day',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='point',
            name='hour',
            field=models.CharField(default='99:99', max_length=5),
        ),
        migrations.AddField(
            model_name='point',
            name='month',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='point',
            name='year',
            field=models.CharField(default='2023', max_length=4),
        ),
    ]
