# Generated by Django 4.2 on 2023-06-04 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0004_rename_hour_point_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='99:99', max_length=5)),
                ('day', models.SmallIntegerField(default=0)),
                ('month', models.SmallIntegerField(default=0)),
                ('year', models.CharField(default='2023', max_length=4)),
                ('type', models.CharField(choices=[('E', 'Entry'), ('P', 'Pause'), ('R', 'Return'), ('Q', 'Quit')], max_length=1)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Refused')], default='P', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
