# Generated by Django 4.2 on 2023-06-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0005_corrections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corrections',
            new_name='Correction',
        ),
    ]
