# Generated by Django 4.2 on 2023-06-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0006_rename_corrections_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='motive',
            field=models.CharField(default='', max_length=100),
        ),
    ]
