# Generated by Django 4.1.4 on 2023-06-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0007_correction_motive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='day',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='correction',
            name='month',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='point',
            name='day',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='point',
            name='month',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
